# Default values for sample-web-app
# This demonstrates how to configure the common library templates

# Global configuration
global:
  env: development
  region: us-west-2
  registry: "your-registry.com"
  imageTag: "latest"

# Application configuration
app:
  name: "sample-web-app"
  version: "1.0.0"
  port: 3000
  healthCheck: "/health"

# Image configuration
image:
  repository: "sample-web-app"
  tag: "1.0.0"
  pullPolicy: IfNotPresent

# Service configuration
service:
  type: ClusterIP
  port: 80
  targetPort: 3000

# Resource limits and requests
resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "250m"
    memory: "256Mi"

# Replica count (overridden by autoscaling if enabled)
replicaCount: 2

# Autoscaling configuration
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

# Ingress configuration
ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  hosts:
    - host: sample-app-dev.example.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: sample-app-tls
      hosts:
        - sample-app-dev.example.com

# Environment variables
env:
  NODE_ENV: development
  API_URL: "https://api-dev.example.com"
  LOG_LEVEL: "info"

# ConfigMap for application configuration
configMap:
  enabled: true
  data:
    database.host: "db-dev.example.com"
    database.port: "5432"
    redis.host: "redis-dev.example.com"
    redis.port: "6379"

# Secrets for sensitive data (base64 encoded values)
secrets:
  enabled: true
  data:
    database.password: "cGFzc3dvcmQxMjM="
    api.key: "YWJjZGVmZ2hpams="

# Service account configuration
serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

# Probe configuration
probes:
  disabled: false
  liveness:
    initialDelaySeconds: 30
    periodSeconds: 20
    timeoutSeconds: 5
    failureThreshold: 3
  readiness:
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
  startup:
    enabled: true
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 30

# Security context
securityContext:
  enabled: true
  runAsNonRoot: true
  runAsUser: 1000
  fsGroup: 2000

# Node selection and scheduling
nodeSelector: {}
tolerations: []
affinity: {}

# Additional labels and annotations
commonLabels: {}
commonAnnotations: {}

podAnnotations: {}
imagePullSecrets: []
