# Default values for common library
# These are base values that can be overridden by consuming charts

# Global configuration
global:
  env: development
  region: us-west-2
  registry: ""
  imageTag: latest

# Application defaults
app:
  name: ""
  version: "1.0.0"
  port: 8080
  healthCheck: "/health"

# Resource defaults
resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "250m"
    memory: "256Mi"

# Autoscaling defaults
autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

# Service defaults
service:
  type: ClusterIP
  port: 80
  targetPort: 8080

# Ingress defaults
ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts: []
  tls: []

# Security context defaults
securityContext:
  enabled: true
  runAsNonRoot: true
  runAsUser: 1000
  fsGroup: 2000

# Node selector and tolerations
nodeSelector: {}
tolerations: []
affinity: {}

# Environment variables
env: {}

# Config maps and secrets
configMap:
  enabled: false
  data: {}

secrets:
  enabled: false
  data: {}
